import Head from 'next/head'
import axios from 'axios'
import { useState } from 'react'

import { Header } from '../components/header'
import { Pokelist } from '../components/pokelist'

export default function Home(props) {
  const [pokes, setPokes] = useState([]);

  //busca em tempo real.
  async function handlerChange(e){
    e.preventDefault();

    const {value} = e.target;

    if (!value) {
      setPokes([]);
      return;
    }

    const queryUrl = `https://api-pokemon-teste-mandarin.herokuapp.com/pokemons?name=${value}`;

    const { data }= await axios.get(queryUrl).catch(err=>err);

    setPokes(data);
  }

  return (
    <>
      <Head>
        <title>PokeSearch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header onChange={handlerChange}/>
      <Pokelist pokes={pokes.length? pokes: props.pokes}/>
    </>
  )
}

//usar o server side pra pegar os valores iniciais
export const getServerSideProps = async () => {
  const response = await axios.get('https://api-pokemon-teste-mandarin.herokuapp.com/pokemons').catch(err=>err);

  const pokes = response.data? response.data:null;

  return {
    props: {
      pokes,
    },
  }
}
